### ISSUE TITLE
predict() fails for type = "coefficients"

### ISSUE THREAD

**Issue by tvedebrink** [Hong-Revo/glmnetUtils#18]
When using the `glmnetUtils:::glmnet.formula` to fit a glmnet model, the `glmnet:::predict` fails for `type = "coefficients"`. It requires a data argument, which is not needed.

**Comment by Hong-Revo** [comment]
If you want coefficients, it's best to use `coef()` which will work without a data argument. This is consistent with how most other model classes handle prediction.

The fact that glmnet allows `type="coefficients"` is kind of a wart; it's there only because the implementation of `coef` is backwards.
