### ISSUE TITLE
Find the best alpha

### ISSUE THREAD

**Issue by privefl** [Hong-Revo/glmnetUtils#19]
Maybe this is stated in the docs but I didn't find it.
How to get the prediction for the best alpha?
When I use `cva.glmnet` and then `predict`, I need to specify `alpha`.
I expected to use the best one (according to the cross-validation).
Should I go through the lists to determine the best one myself?

**Comment by Hong-Revo** [comment]
I didn't implement automatically choosing a value of alpha, because crossvalidation is often a very noisy procedure -- especially when selecting 2 parameters (alpha, lambda) and when the dataset is small. What I'd recommend is choosing alpha manually by plotting the cva.glmnet result and looking at the curve. Or, if you want an automated procedure, run cva.glmnet multiple times and take the average best alpha.

**Comment by krz** [comment]
I agree with @privefl , there should be an automated procedure to get the best alpha.

**Comment by privefl** [comment]
@krz Have a look at [this](https://privefl.github.io/blog/choosing-hyper-parameters-in-penalized-regression/).
